<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Customer\Block\Account\AuthorizationLink $block */

$dataPostParam = '';
if ($block->isLoggedIn()) {
    $dataPostParam = sprintf(" data-post='%s'", $block->getPostParams());
}
?>
<a <?= /* @noEscape */ $block->getLinkAttributes() ?><?= /* @noEscape */ $dataPostParam ?> style="display:flex;align-items: center;">
    <span style="margin-right: 15px;font-size: 110%;"><?= $block->escapeHtml(__('Login')) ?></span>
    <img src="<?php echo $block->escapeUrl($block->getViewFileUrl('images/user.png'))?>">
</a>

